### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'timestamp'

### ISSUE THREAD

**Issue by chinchunchang** [zsxsoft/my-beancount-scripts#24]
之前用的老版的脚本，从网页端导出的支付宝账单没问题。最近看到脚本和beancount都更新了就新建了个vm新装了依次，安装好依赖之后从手机导出账单，执行脚本时出现如下错误：
root@ubuntu:~/bookkeeping# python3 importers/main/import.py documents.tmp/alipay/alipay_record_2018.csv
Not Alipay Trade Record!
Import Alipay
Importing 余额宝-2018.12.30-收益发放 at 2018-12-31 04:53:46
Traceback (most recent call last):
  File "/root/bookkeeping/importers/main/import.py", line 46, in <module>
    new_entries = instance.parse()
  File "/root/bookkeeping/importers/main/modules/imports/alipay_prove.py", line 53, in parse
    meta['timestamp'] = str(time.timestamp()).replace('.0', '')
AttributeError: 'NoneType' object has no attribute 'timestamp'
非计算机专业，建筑狗一个，不是很懂，大神帮忙啊

**Comment by zsxsoft** [comment]
看看这一行的内容

**Comment by chinchunchang** [comment]
意思是说账单里没时间戳么？

**Comment by chinchunchang** [comment]
又重新试了下，发现是时区的问题。系统时间为非UTC时区的时候就会出现以上错误提示。我也不懂如何修改，那就干脆不换时区好了😀
